### health check
GET http://localhost:5000/health-check HTTP/1.1

### registration
POST http://localhost:5000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{   
    "firstname": "Test",
    "lastname": "Test",
    "username": "test15",
    "email": "test15@gmail.com",
    "password": "1234"
}

### login
POST http://localhost:5000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{   
    "email": "steveroger@gmail.com",
    "password": "1234"
}

### refresh token
POST http://localhost:5000/api/v1/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTcwMDM5MzY3NSwiZXhwIjoxNzAwMzk3Mjc1LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.HeVZz7VLat9OChq2JGKTvlygqwolzk2lA2ei5PUEwzk"
}

### logout
DELETE http://localhost:5000/api/v1/auth/logout HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzUxZDBkYWFlNjIxNDhkMDkxMGQ2MiIsImVtYWlsIjoicnVieXJveUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNjk4MjMyOTkxLCJleHAiOjE3Mjk3OTA1OTEsImF1ZCI6IjY1MzUxZDBkYWFlNjIxNDhkMDkxMGQ2MiIsImlzcyI6Im5leHVzLnJhZ2h1Z2FubmFyYW0uY29tIn0.j-CddZeB-SLPep0_13djIoYTTADiVyH1EOAceBfbRqA"
}

### all users
GET http://localhost:5000/api/v1/user/all HTTP/1.1

### user by id
GET http://localhost:5000/api/v1/user/65351d0daae62148d0910d62 HTTP/1.1

### update user
PUT http://localhost:5000/api/v1/user/65351d0daae62148d0910d62 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzUxZDBkYWFlNjIxNDhkMDkxMGQ2MiIsImVtYWlsIjoicnVieXJveUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNjk4MjA4NTA2LCJleHAiOjE3Mjk3NjYxMDYsImF1ZCI6IjY1MzUxZDBkYWFlNjIxNDhkMDkxMGQ2MiIsImlzcyI6Im5leHVzLnJhZ2h1Z2FubmFyYW0uY29tIn0.P1TkneC_R1iYIA8fi_74yJkWVIOkV8CmYnPv8w__X4k
Content-Type: application/json

{   
    "updatedData": {
        "firstname": "Ruby",
        "lastname": "Roy",
        "username": "ruby"
    }
}

### follow user
PUT http://localhost:5000/api/v1/user/follow/653502d705e5b242386e7377 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzUxZDBkYWFlNjIxNDhkMDkxMGQ2MiIsImVtYWlsIjoicnVieXJveUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2OTgyMDg1MDYsImV4cCI6MTY5ODIxMjEwNiwiYXVkIjoiNjUzNTFkMGRhYWU2MjE0OGQwOTEwZDYyIiwiaXNzIjoibmV4dXMucmFnaHVnYW5uYXJhbS5jb20ifQ.nzsPchU1IY5jMddalhrremzkxG-NZxSPHRfsTh-cfHI

### delete user
DELETE http://localhost:5000/api/v1/user/6537a98faefbcf436c83db72 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzdhOThmYWVmYmNmNDM2YzgzZGI3MiIsImVtYWlsIjoidGVzdDNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNjk4MjExNDM0LCJleHAiOjE2OTgyMTUwMzQsImF1ZCI6IjY1MzdhOThmYWVmYmNmNDM2YzgzZGI3MiIsImlzcyI6Im5leHVzLnJhZ2h1Z2FubmFyYW0uY29tIn0.UQ-rdG4Gn5RMJn85idHXPtf3Wc4r4bWW8FjTKTzgPfY


### all posts
GET http://localhost:5000/api/v1/post/all HTTP/1.1

### post by id
GET http://localhost:5000/api/v1/post/6538fe99b657164e60279fc8 HTTP/1.1

### create post
POST http://localhost:5000/api/v1/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1ODM5OCwiZXhwIjoxNjk4MjYxOTk4LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.Wb7iLGlqlm_ECG5o4hxGOtzE5NA3x1E0OtV0zMfoFXo
Content-Type: application/json

{
    "description": "I am Iron Man."
}

### update post
PUT http://localhost:5000/api/v1/post/6538ffe7b657164e60279fd5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsIm5hbWUiOiJ1bmRlZmluZWQgdW5kZWZpbmVkIiwiZW1haWwiOiJ0b255c3RhcmtAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNjk4MjM4NDEwLCJleHAiOjE2OTgyNDIwMTAsImF1ZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsImlzcyI6Im5leHVzLnJhZ2h1Z2FubmFyYW0uY29tIn0.qr7PcOWMSQTPgnQEHjAG6Tty-AXzjuF-qCHYQbJH3Cw
Content-Type: application/json

{
    "description": "I'm not a hero. I'm a high-functioning sociopath."
}

### delete post
DELETE http://localhost:5000/api/v1/post/653917d64bb4c4528cff8b78 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsIm5hbWUiOiJ1bmRlZmluZWQgdW5kZWZpbmVkIiwiZW1haWwiOiJ0b255c3RhcmtAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNjk4MjM4NDEwLCJleHAiOjE2OTgyNDIwMTAsImF1ZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsImlzcyI6Im5leHVzLnJhZ2h1Z2FubmFyYW0uY29tIn0.qr7PcOWMSQTPgnQEHjAG6Tty-AXzjuF-qCHYQbJH3Cw


### all comments
GET http://localhost:5000/api/v1/post/comment/6538ff5bb657164e60279fcf HTTP/1.1

### create comment
POST http://localhost:5000/api/v1/post/comment/6538ff5bb657164e60279fcf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsIm5hbWUiOiJUb255IFN0YXJrIiwiaGFuZGxlIjoidG9ueSIsImVtYWlsIjoidG9ueXN0YXJrQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1NDY1NSwiZXhwIjoxNjk4MjU4MjU1LCJhdWQiOiI2NTM3N2IxNzlmYjM0MzA5YWM2NDdmN2IiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.f_ad89MGi0cFYWRcZouxzdtazScc9w63KWGUbrbipGo
Content-Type: application/json

{
    "description": "Rogered that!"
}

### update comment
PUT http://localhost:5000/api/v1/post/comment/6538ff5bb657164e60279fcf/653954472429252920c97435 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsIm5hbWUiOiJUb255IFN0YXJrIiwiaGFuZGxlIjoidG9ueSIsImVtYWlsIjoidG9ueXN0YXJrQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1NDY1NSwiZXhwIjoxNjk4MjU4MjU1LCJhdWQiOiI2NTM3N2IxNzlmYjM0MzA5YWM2NDdmN2IiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.f_ad89MGi0cFYWRcZouxzdtazScc9w63KWGUbrbipGo
Content-Type: application/json

{
    "description": "Rogered that! Over and out!"
}

### delete comment
DELETE http://localhost:5000/api/v1/post/comment/6538ff5bb657164e60279fcf/653953ca7036d94a685f7c8e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YjE3OWZiMzQzMDlhYzY0N2Y3YiIsIm5hbWUiOiJUb255IFN0YXJrIiwiaGFuZGxlIjoidG9ueSIsImVtYWlsIjoidG9ueXN0YXJrQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1NDY1NSwiZXhwIjoxNjk4MjU4MjU1LCJhdWQiOiI2NTM3N2IxNzlmYjM0MzA5YWM2NDdmN2IiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.f_ad89MGi0cFYWRcZouxzdtazScc9w63KWGUbrbipGo

### like post
PUT http://localhost:5000/api/v1/post/like/6538ff99b657164e60279fd2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1ODM5OCwiZXhwIjoxNjk4MjYxOTk4LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.Wb7iLGlqlm_ECG5o4hxGOtzE5NA3x1E0OtV0zMfoFXo

### like comment
PUT http://localhost:5000/api/v1/post/comment-like/6538ff5bb657164e60279fcf/653953ec7036d94a685f7c91
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1ODM5OCwiZXhwIjoxNjk4MjYxOTk4LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.Wb7iLGlqlm_ECG5o4hxGOtzE5NA3x1E0OtV0zMfoFXo

### timeline
GET http://localhost:5000/api/v1/post/timeline HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1ODM5OCwiZXhwIjoxNjk4MjYxOTk4LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.Wb7iLGlqlm_ECG5o4hxGOtzE5NA3x1E0OtV0zMfoFXo

### user posts
GET http://localhost:5000/api/v1/post/personal/65377b179fb34309ac647f7b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzc3YWQwOWZiMzQzMDlhYzY0N2Y3NSIsIm5hbWUiOiJTdGV2ZSBSb2dlciIsImhhbmRsZSI6InN0ZXZlIiwiZW1haWwiOiJzdGV2ZXJvZ2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTY5ODI1ODM5OCwiZXhwIjoxNjk4MjYxOTk4LCJhdWQiOiI2NTM3N2FkMDlmYjM0MzA5YWM2NDdmNzUiLCJpc3MiOiJuZXh1cy5yYWdodWdhbm5hcmFtLmNvbSJ9.Wb7iLGlqlm_ECG5o4hxGOtzE5NA3x1E0OtV0zMfoFXo